project_id = "axykpiouydopghiiqgbi"

[functions.match-sounds]
verify_jwt = false

[functions.deity-chat]
verify_jwt = false

[functions.deity-parameters]
verify_jwt = false

[functions.deity-voice]
verify_jwt = false

[functions.opening-prophecy]
verify_jwt = false
